#!/bin/sh

# Script to do one-touch deployment of code in git repos: see README for
# details.
#
# Copyright 2011 Miles Gould. This program is free software: see COPYING for
# details.

die() {
	echo $1 >&2
	exit 1
}

configure_host() {
	echo -n "Enter host to deploy to: "
        read HOST
        git config --add deploy.host "$HOST"
}

configure_dir() {
        echo -n "Enter directory to deploy to on $HOST: "
        read DIR
        git config --add deploy.dir "$DIR"
}

HOST=`git config --get deploy.host` || configure_host
while [ -z "$HOST" ]; do
	echo "deploy.host should be nonempty." >&2
	configure_host
done

DIR=`git config --get deploy.dir`   || configure_dir
# It's totally OK for DIR to be empty; it just means you're deploying to $HOME.

CMD_NAME=`basename "$0"`
if [ "$CMD_NAME" = "git-deploy" ]; then
	git push || die "Couldn't push!"
	ssh $HOST "cd $DIR && git pull"
elif [ "$CMD_NAME" = "git-undeploy" ]; then
	ssh $HOST "cd $DIR && git checkout HEAD@{1} \
			&& git branch -f master HEAD && git checkout master"
else
	die "Command $0 not recognised."
fi
