#!/bin/sh

# Script to do one-touch deployment of code in git repos: see README for
# details.
#
# Copyright 2011 Miles Gould. This program is free software: see COPYING for
# details.

die() {
	echo $1 >&2
	exit 1
}

HOST=`git config --get deploy.host` || die "deploy.host not set!"
DIR=`git config --get deploy.dir`   || die "deploy.dir not set!"
if [ -z "$HOST" ]; then
	echo "deploy.host should be nonempty." >&2
	exit 3
fi
# It's totally OK for DIR to be empty; it just means you're deploying to $HOME.

CMD_NAME=`basename "$0"`
if [ "$CMD_NAME" = "git-deploy" ]; then
	git push || die "Couldn't push!"
	ssh $HOST "cd $DIR && git pull"
elif [ "$CMD_NAME" = "git-undeploy" ]; then
	ssh $HOST "cd $DIR && git checkout HEAD@{1} \
			&& git branch -f master HEAD && git checkout master"
else
	die "Command $0 not recognised."
fi
